# Example services.yaml entry

# Service ID
set_current_limit:
  # Different fields that your service action accepts
  fields:
    # Key of the field
    current:
      # Whether or not field is required (default = false)
      required: true
      # Example value that can be passed for this field
      example: "6000"
      # The default field value
      default: "6000"
      # Selector (https://www.home-assistant.io/docs/blueprint/selectors/) to control
      # the input UI for this field
      selector:
        number:
          min: 1
          max: 32000
